export enum SelectorType {
  NAME = 'NAME',
  TITLE = 'TITLE',
  SUMMARY = 'SUMMARY',
  EMAIL = 'EMAIL',
  LOCATION = 'LOCATION',
  PHONE = 'PHONE',
  SOCIAL_LIST = 'SOCIAL_LIST',
  SOCIAL_ICON = 'SOCIAL_ICON',
  SOCIAL_NAME = 'SOCIAL_NAME',
  SOCIAL_URL = 'SOCIAL_URL',
  EXPERIENCE_LIST = 'EXPERIENCE_LIST',
  EXPERIENCE_TITLE = 'EXPERIENCE_TITLE',
  EXPERIENCE_DURATION = 'EXPERIENCE_DURATION',
  EXPERIENCE_ORGANIZATION = 'EXPERIENCE_ORGANIZATION',
  EXPERIENCE_LOCATION = 'EXPERIENCE_LOCATION',
  EXPERIENCE_DESCRIPTION_LIST = 'EXPERIENCE_DESCRIPTION_LIST',
  EXPERIENCE_DESCRIPTION = 'EXPERIENCE_DESCRIPTION',
  EXPERIENCE_SKILL_LIST = 'EXPERIENCE_SKILL_LIST',
  EXPERIENCE_SKILL = 'EXPERIENCE_SKILL',
  SKILL_LIST = 'SKILL_LIST',
  SKILL_NAME = 'SKILL_NAME',
  SKILL_PROFICIENCY = 'SKILL_PROFICIENCY',
  CERTIFICATION_LIST = 'CERTIFICATION_LIST',
  CERTIFICATION_TITLE = 'CERTIFICATION_TITLE',
  CERTIFICATION_YEAR = 'CERTIFICATION_YEAR',
  CERTIFICATION_ORGANIZATION = 'CERTIFICATION_ORGANIZATION',
  CERTIFICATION_LOCATION = 'CERTIFICATION_LOCATION',
}

export function selectorTypesByListType(type: SelectorType) {
  switch(type) {
    case SelectorType.SOCIAL_LIST:
      return [
        SelectorType.SOCIAL_ICON,
        SelectorType.SOCIAL_NAME,
        SelectorType.SOCIAL_URL,
      ];
    case SelectorType.EXPERIENCE_LIST:
      return [
        SelectorType.EXPERIENCE_TITLE,
        SelectorType.EXPERIENCE_DURATION,
        SelectorType.EXPERIENCE_ORGANIZATION,
        SelectorType.EXPERIENCE_LOCATION,
        SelectorType.EXPERIENCE_DESCRIPTION,
        SelectorType.EXPERIENCE_SKILL,
      ];
    case SelectorType.SKILL_LIST:
      return [
        SelectorType.SKILL_NAME,
        SelectorType.SKILL_PROFICIENCY,
      ];
    case SelectorType.CERTIFICATION_LIST:
      return [
        SelectorType.CERTIFICATION_TITLE,
        SelectorType.CERTIFICATION_YEAR,
        SelectorType.CERTIFICATION_ORGANIZATION,
        SelectorType.CERTIFICATION_LOCATION,
      ];
    default:
      throw Error("Unknown type");
  };
}
